AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31


Resources:
  ScrapyFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Timeout: 15
      MemorySize: 512
      Events:
        WebEndpoint:
          Type: Api
          Properties:
            Path: /scrape
            Method: get
      Environment:
        Variables:
          DESTINATION_BUCKET: !Ref DestinationBucket
      Policies:
        - S3WritePolicy:
            BucketName: !Ref DestinationBucket
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./src
      DockerTag: python3.9-v1

  DestinationBucket:
    Type: AWS::S3::Bucket

Outputs:
  ScrapyApi:
    Description: "API Gateway endpoint URL for Prod stage for Scrapy function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/scrape/"
  BucketName:
    Value: !Ref DestinationBucket
    Description: Name of the Amazon S3 bucket
